### PR TITLE
Add categories, Remove categories, Add descriptions, Recategorize

### PR DESCRIPTION
**Pull request by bibbca**
Add Categories:
- News
- Games
- Go
- Video

Remove Categories:
- Profile
- Fun

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
Really like the new categories. Looks perfect @bibbca 🙂

**Comment by nikitavoloboev** [comment]
Only thing is that we should probably move `# Games` to [games list](https://github.com/learn-anything/games#readme) instead.

**Comment by nikitavoloboev** [comment]
There are some conflicts though. Can you try resolve them?

**Comment by bibbca** [comment]
Done :)

**Comment by nikitavoloboev** [comment]
Awesome 🎊

**Pull request merged**
