### PR TITLE
Added Descriptions, Moved links to Russian Category as Appropriate.

### PR DESCRIPTION
**Pull request by bibbca**

### CODE REVIEW

**Comment by nikitavoloboev** [comment]
This is amazing. Thank you very much @bibbca 💜

**Comment by nikitavoloboev** [comment]
One advice I have is to make commits in imperative tense. `Added Descriptions` -> `Add descriptions`.

This image is pretty good. 🙂

**Comment by bibbca** [comment]
Thanks for the info, I'm still learning this git process.  Thanks for the critique and the excellent project :)

**Comment by nikitavoloboev** [comment]
I moved the `Apps` sections from here and transferred the apps to another [macOS-apps](https://github.com/learn-anything/macos-apps#interesting-macos-apps-) list as it fits it more.

It's best we keep each curated list focused so not to repeat entries from [other lists](https://github.com/learn-anything/curated-lists).

This particular list is a bit messy and really needs to be structured well. Currently the groupings are not as clear and maybe even repeating. I tried to fix some things but there's still lot's to do.

**Pull request merged**
